# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='path',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.TextField(unique=True),
        ),
    ]
