# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171010_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'permissions': (('view_directory', 'View Directory'),)},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('view_file', 'View file'),)},
        ),
    ]
